# Site settings
baseurl = "//bible.hightower.space/"
languageCode = "en"
title = "Bible Research"
theme = "hugo-theme-cactus-plus"

[params]
    author = "Floyd Hightower"
    description = "Bible Research"
    bio = "\"In your thinking be mature\""

    enableRSS = true
    enableToc = true

    enableDisqus = false
    disqusShortname = "your_disqus_short_name"

    enableSummary = true
    # Set the value to true if use description in post front matter replace content summary
    useDescriptionReplaceSummary = true

    enableTwitterCard = true
    # The url for twitter card image, default is avatar.png in static/images directory
    twitterCardImage = "./static/images/avatar.jpeg"

    # Add custom assets with their paths relative to the static folder
    customCSS = []
    customJS  = []

    # The variables below are optionally too and can be used to
    # translate or customize each string of the theme.

    # Navigation links
    home = ""
    about = ""
    archive = ""
    subscribe = ""

    olderPosts = ""
    newerPosts = ""
    copyright = ""

    # show latest posts in single page
    showLatestPosts = false
    readMore = ""

    # 404 page
    title404 = ""
    subtitle404 = ""
